### ISSUE TITLE
Space between spans

### ISSUE THREAD

**Issue by ntopulos** [jimblue/grav-plugin-minify-html#1]
Hello,
The plugin works pretty well, but I've encountered an issue with my layout: two `<span>` pairs separated by a space lose this space during minification. In result, two words are merged into one.

Input:

    <p>
        <span>electron</span>
        <span>proton</span>
    </p>

Output:

    <p><span>electron</span><span>proton</span></p>

**Comment by jimblue** [comment]
Hi @ntopulos !
Why don't you try this:

`<p>
    <span>electron </span>
    <span>proton</span>
</p>`

**Comment by gamag** [comment]
https://github.com/WyriHaximus/HtmlCompress/issues/27
