### ISSUE TITLE
Cache compression output

### ISSUE THREAD

**Issue by DanielSokil** [jimblue/grav-plugin-minify-html#11]
Does this plugin cache compression, or it runs on every request?

**Comment by jimblue** [comment]
Fixed in last release [V1.0.3](https://github.com/jimblue/grav-plugin-minify-html/releases/tag/1.0.3) with a new option to cache the compression 🎉 🎉 🎉 !!!

**Comment by DanielSokil** [comment]
Thanks so much! Server response time is now 30-40ms less.
