### ISSUE TITLE
Plugin doesn't work with Grav >1.6

### ISSUE THREAD

**Issue by tschugun** [jimblue/grav-plugin-minify-html#16]
Plugin just stopped working after Grav 1.6 update.

nginx/FPM
PHP v.7.1.28
Grav v1.6.6

**Comment by taver** [comment]
Any updates ?

**Comment by jimblue** [comment]
Hi everyone,

Sorry I don't have time right now to update the plugin, I'll do it as soon as I can.
I suggest you guys to simply disable the plugin while waiting for a new compatible release.

That say if someone want to create a PR I would be happy to look at it.

Cheers!

**Comment by jimblue** [comment]
Fixed with the latest release [Grav Minify html 1.1.2](https://github.com/jimblue/grav-plugin-minify-html/releases/tag/1.1.2) !!
