### ISSUE TITLE
error on readme.md

### ISSUE THREAD

**Issue by heliogabal** [jimblue/grav-plugin-minify-html#4]
Hi, 
thanks for the plugin, just what I was looking for. I only had some trouble installing it. It seems you renamed the plugin, so the documentation seems out of sync... Should be `bin/gpm install minify-html` instead of `bin/gpm install minifyhtml`, and the respective plugin is going to be installed in `your/site/grav/user/plugins/minify-html`.

**Comment by jimblue** [comment]
Fixed! Thanks @heliogabal

**Comment by heliogabal** [comment]
Thank you!
