### ISSUE TITLE
Linebreaks should translate to spaces

### ISSUE THREAD

**Issue by gamag** [jimblue/grav-plugin-minify-html#6]
Thank you for your work!

Sadly, the plugin breaks my page layout, since it removes spaces and line breaks entirely between two elements I need separated:

`<li>a</li>  [many white-spaces characters]  <li>b</li>` correctly results in `<li>a</li> <li>b</li>`, but something like
```
 <li>a</li>
       <li>b</li>
```
gives `<li>a</li><li>b</li>`.
For the output to behave like the original HTML, there should be a space between closing and opening tag.

**Comment by jimblue** [comment]
Hi @gamag and sorry for the delay!

Because of too many random problems with compression I've just changed how HTML-JS-CSS are compressed by using an external library.

The result is better in many ways but it's now impossible know to toggle JS or CSS compression.

Your problem should be fixed with the last release [0.0.5](https://github.com/jimblue/grav-plugin-minify-html/releases/tag/0.0.5) (should be online tomorrow)

Cheers

**Comment by gamag** [comment]
Thank you for the update!

However, it seems still to be broken, not only with line breaks, but even with only spaces between the tags.

Currently, I need one space to be left between tags because I use a text-align: justify; hack to distribute them evenly in the parent element, but since it is standard, I'd generally rely on spaces to separate inline elements. For example what about two font-awesome icons next to each other? Here having a space between the two `<i>` tags (or whatever you use) seems to be the only correct way to separate them in a text...

**Comment by jimblue** [comment]
This is not broken at all this is the normal behaviour for a compressor to remove unused space between tag. It's impossible to guess that's they have a design purpose. That's why CSS exist, to separate style from the rest.

Just remove the spaces between tags and add CSS rule to get what you want.

**Comment by jimblue** [comment]
About icon use margin left or right to space them with a CSS class. Really that's the best solution, you should stop using space as a styling tool!

**Comment by gamag** [comment]
Well, you are right that margins are the way to go in may cases, however what I meant with the icons is that, if you use them like letters or words in a text, the spacing should be determined by the layout algorithm, not manually by margins.

In the other case I described - I don't know a better portable way to get elements of unknown number and width distributed evenly, with the first one right at the beginning and the last one right at the end of the line than using css `text-align: justify;` with some hack to get a invisible second line of "text"... 

Concerning the "normal" behavior of a compressor - I think a good compressor should not change the semantics of the original html - so an one-space text node has to be left between elements originally separated by (multiple) spaces or line-breaks, just as you would not change the functionally of js when compressing it.

**Comment by jimblue** [comment]
Again you're thinking this wrongly...
This wont work because the space is between tag:

`<div><span>some text</span> <i class="icon"></div>`

but this will with space just after some text:

`<div><span>some text </span><i class="icon"></div>`

Anyway, as I told you there is nothing to fixe here in this plugin. Change your code or don't use it.

**Comment by gamag** [comment]
What about `<p>some text <i class="icon1"></i> <i class="icon2"></i> more text</p>`. Having the space inside the first `<i>` would be weird.

If you could help me with this, I could "correct" my code: 
`<div><span>ABC</span><span>Hello World</span><span>span span span</span><span>vwxyz</span></div>` 
The spans should be distributed as explained in my last reply, portable, css-only...

I'll ask the people from the library you now use to fix this, probably the problem is in their code. Thanks for your work.

**Comment by gamag** [comment]
https://github.com/WyriHaximus/HtmlCompress/issues/27
