### ISSUE TITLE
Breaks the Diagrams Plugin

### ISSUE THREAD

**Issue by iz7iz7iz** [jimblue/grav-plugin-minify-html#7]
When activated this plugin unfortunately breaks the Grav Diagrams Plugin.

Is there any workaround for this?

**Comment by jimblue** [comment]
This plugin now depend on [WyriHaximus/HtmlCompress](https://github.com/WyriHaximus/HtmlCompress) for compression.

That mean the output of the Grav Diagram Plugin is not compatible with `WyriHaximus/HtmlCompress` somehow.

It's impossible to guess why it's the case without more informations. I advice you to look for the first compression break of Grav Diagram Plugin output.

You should then compare your finding with the issues of [WyriHaximus/HtmlCompress](https://github.com/WyriHaximus/HtmlCompress).

**Comment by jimblue** [comment]
@iz7iz7iz can you try the new version and test the different compression type to see if it's solve your problem?

**Comment by iz7iz7iz** [comment]
hi, thank you very much for update.

i saw the update on the management panel.
while updating i got the error about zip-archive, so i installed php7.1-zip on the server
then i could successfully updated the plugin.

i tried all the compression modes without cache, all with no luck.

the error on the console:

```javascript
Uncaught TypeError: Cannot read property 'key' of null
    at getDisplaySymbol (21fc04d804ac8b3f7ee829696c7ff074.js:17)
    at constructChart (21fc04d804ac8b3f7ee829696c7ff074.js:19)
    at Object.drawSVG (21fc04d804ac8b3f7ee829696c7ff074.js:19)
    at HTMLDocument.<anonymous> (ozet:13)
    at i (21fc04d804ac8b3f7ee829696c7ff074.js:1)
    at Object.fireWith [as resolveWith] (21fc04d804ac8b3f7ee829696c7ff074.js:1)
    at Function.ready (21fc04d804ac8b3f7ee829696c7ff074.js:1)
    at HTMLDocument.J (21fc04d804ac8b3f7ee829696c7ff074.js:1)
```

**Comment by jimblue** [comment]
Hi @iz7iz7iz !

I suggest you to report this Bug to [WyriHaximus/HtmlCompress ](https://github.com/WyriHaximus/HtmlCompress) repo as the compression only rely on this library.

@WyriHaximus is a very nice guy and will probably be interested about this bug.

Keep this open until you give me some news about this.

Cheers

**Comment by jimblue** [comment]
Hi @iz7iz7iz can you please try last release and tell me if it fix your problem?
https://github.com/jimblue/grav-plugin-minify-html/releases/tag/0.0.8

**Comment by jimblue** [comment]
Closing this for now as I don't have feedback for too long. Thanks to come back with more informations to re open.
