### ISSUE TITLE
Lock to PHP 5.5

### ISSUE THREAD

**Issue by WyriHaximus** [jimblue/grav-plugin-minify-html#8]
With the upcoming bump to PHP 5.6 in html-compress 1.4 I strongly suggest adding a snippet like [this](https://github.com/WyriHaximus/HtmlCompress/blob/f2ac148117228ad86f877c2f4cd6d733fffcf295/composer.json#L40-L45) to composer.json ensuring your plugin doesn't accidently bumps over the minimum of [PHP 5.5 by grav](https://github.com/getgrav/grav/blob/develop/composer.json#L10)

**Comment by jimblue** [comment]
That's very kind of you 😄 !

I'll add this right now

**Comment by WyriHaximus** [comment]
No problem :+1:
