### ISSUE TITLE
Support fastest, default, and smallest modes

### ISSUE THREAD

**Issue by WyriHaximus** [jimblue/grav-plugin-minify-html#9]
Looking at your code [you only use](https://github.com/jimblue/grav-plugin-minify-html/blob/master/minify-html.php#L58) the default mode which does compress JS and CSS but doesn't do it aggressively to get the smallest size. There is also a [fastest](https://github.com/WyriHaximus/HtmlCompress/blob/master/src/Factory.php#L31) constructor which only compresses HTML and ignores the rest. And a [smallest](https://github.com/WyriHaximus/HtmlCompress/blob/master/src/Factory.php#L102) which goes after the smallest possible size with the available compressors. Maybe an extra option could expose this to your users?

**Comment by jimblue** [comment]
Oh I didn't even knew about those option! How should I use them, I didn't found any info in your doc.

**Comment by WyriHaximus** [comment]
Yeah I'll be updating the docs soon :zipper_mouth_face: .  My suggestion would be to keep the current the default and add an option for both fastest and smallest. The smallest brings a bit more risk with it since there is currently no checking on valid CSS and JS.

**Comment by jimblue** [comment]
Yep I tough the same about default.

Could you tell me now how to use fastest and smallest? (I'm motivated to do it now haha)

**Comment by WyriHaximus** [comment]
Call `constructSmallest` or `constructFastest` instead of `construct` on the factory.

**Comment by jimblue** [comment]
easy 😄 !

**Comment by jimblue** [comment]
Just did it but still not compressing JSON-LD, even with smallest, any idea why? It's working on your side?

**Comment by jimblue** [comment]
@WyriHaximus I've just update the code (you can check develop branch).

But still, it's not compressing `JSON-LD`, even with `smallest` setting... Any idea why it's not working?
